"""
Django settings for Project_tracker project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1%%hsrkx_tbxht^6e+3$9rhqsg&j_^b2ws14b7_ds(^(4#gx6_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tracker',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Project_tracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Project_tracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# Only needed if you want to use custom static directories
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Add your project's static directory
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "Project Tracker Admin",
    "site_header": "Project Tracker",
    "site_brand": "Project Tracker",
    "welcome_sign": "Welcome to Project Tracker Admin",
    'custom_base_template': 'admin/custom_base_site.html',
    "show_sidebar": True,
    "navigation_expanded": True,
    "custom_css": "admin/css/baseCustom.css",
    "order_with_respect_to": ["tracker"],  # Makes tracker app appear first
    "apps_order": ["auth", "tracker"],  # Explicitly include 'tracker' app
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Projects", "url": "admin:tracker_project_changelist", "permissions": ["tracker.view_project"]},  # Add this line
    ],
    "usermenu_links": [
        {"name": "Support", "url": "https://support.example.com", "new_window": True},
    ],
    "icons": {
        "tracker.Project": "fas fa-project-diagram",
        "tracker.Task": "fas fa-tasks",
        "auth.User": "fas fa-users",  # Icon for User model
    },
    "order_with_respect_to": ["tracker.Project", "tracker.Task"],
    "side_menu": [
        # User Profile Section
        {
            "name": "Tracker", 
            "icon": "fas fa-tasks",  # Icon for Tracker
            "children": [
                {
                    "name": "Projects", 
                    "url": "admin:tracker_project_changelist",  # URL for the Project change list
                    "icon": "fas fa-project-diagram",  # Icon for Projects
                },
                # You can add other sections like "Tasks" or "Sprints" here if needed
            ]
        },
        {"name": "Users", "url": "admin:auth_user_changelist", "icon": "fas fa-users"},
        {"name": "Groups", "url": "admin:auth_group_changelist", "icon": "fas fa-users-cog"},
        # More menu items here
    ],
}


