# Generated by Django 4.2.17 on 2024-12-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_sprint_task_alter_project_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='screenshots',
            field=models.ImageField(blank=True, null=True, upload_to='task_screenshots/'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='To Do', max_length=20),
        ),
    ]
